
package com.exemple.generate;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CommandWsImplService", targetNamespace = "http://command_web_service.example.com/", wsdlLocation = "http://localhost:8081/ws/service-command?wsdl")
public class CommandWsImplService
    extends Service
{

    private final static URL COMMANDWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException COMMANDWSIMPLSERVICE_EXCEPTION;
    private final static QName COMMANDWSIMPLSERVICE_QNAME = new QName("http://command_web_service.example.com/", "CommandWsImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/ws/service-command?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMMANDWSIMPLSERVICE_WSDL_LOCATION = url;
        COMMANDWSIMPLSERVICE_EXCEPTION = e;
    }

    public CommandWsImplService() {
        super(__getWsdlLocation(), COMMANDWSIMPLSERVICE_QNAME);
    }

    public CommandWsImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMMANDWSIMPLSERVICE_QNAME, features);
    }

    public CommandWsImplService(URL wsdlLocation) {
        super(wsdlLocation, COMMANDWSIMPLSERVICE_QNAME);
    }

    public CommandWsImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMMANDWSIMPLSERVICE_QNAME, features);
    }

    public CommandWsImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CommandWsImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CommandWs
     */
    @WebEndpoint(name = "CommandWsImplPort")
    public CommandWs getCommandWsImplPort() {
        return super.getPort(new QName("http://command_web_service.example.com/", "CommandWsImplPort"), CommandWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CommandWs
     */
    @WebEndpoint(name = "CommandWsImplPort")
    public CommandWs getCommandWsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://command_web_service.example.com/", "CommandWsImplPort"), CommandWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMMANDWSIMPLSERVICE_EXCEPTION!= null) {
            throw COMMANDWSIMPLSERVICE_EXCEPTION;
        }
        return COMMANDWSIMPLSERVICE_WSDL_LOCATION;
    }

}
